const descriptions = {
  "2 door/bottom drawers/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/bottom drawers/one short mirror.webp": "Enhance your bedroom with this elegant one short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/bottom drawers/two short mirror.webp": "Enhance your bedroom with this elegant two short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/combi/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/combi/one long and one short mirror.webp": "Enhance your bedroom with this elegant one long and one short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/combi/one long mirror.webp": "Enhance your bedroom with this elegant one long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/sets/set1.webp": "Enhance your bedroom with this elegant set1. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/sets/set2.webp": "Enhance your bedroom with this elegant set2. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/sets/set3.webp": "Enhance your bedroom with this elegant set3. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/simple/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/simple/one long mirror.webp": "Enhance your bedroom with this elegant one long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "2 door/simple/two long mirror.webp": "Enhance your bedroom with this elegant two long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/bottom drawers/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/bottom drawers/one short mirror.webp": "Enhance your bedroom with this elegant one short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/bottom drawers/two short mirror.webp": "Enhance your bedroom with this elegant two short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/sets/set1.webp": "Enhance your bedroom with this elegant set1. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/simple/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/simple/one long mirror.webp": "Enhance your bedroom with this elegant one long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "3 door/simple/three long mirror.webp": "Enhance your bedroom with this elegant three long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/bottom drawers/four short mirror.webp": "Enhance your bedroom with this elegant four short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/bottom drawers/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/bottom drawers/two short mirror.webp": "Enhance your bedroom with this elegant two short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/sets/set1.webp": "Enhance your bedroom with this elegant set1. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/sets/set2.webp": "Enhance your bedroom with this elegant set2. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/simple/four long mirror.webp": "Enhance your bedroom with this elegant four long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/simple/no mirror.webp": "Enhance your bedroom with this elegant no mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "4 door/simple/two long mirror.webp": "Enhance your bedroom with this elegant two long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "5 door/bottom drawers/one long and two short mirror.webp": "Enhance your bedroom with this elegant one long and two short mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "5 door/bottom drawers/one long mirror.webp": "Enhance your bedroom with this elegant one long mirror. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "5 door/sets/set1.webp": "Enhance your bedroom with this elegant set1. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/bottom drawers/four long and two short mirror with two bottom drawers.webp": "Enhance your bedroom with this elegant four long and two short mirror with two bottom drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/bottom drawers/two long and two short mirror with three bottom drawers.webp": "Enhance your bedroom with this elegant two long and two short mirror with three bottom drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/bottom drawers/two short mirror and three bottom drawers.webp": "Enhance your bedroom with this elegant two short mirror and three bottom drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/bottom drawers/two short mirror and two bottom drawers.webp": "Enhance your bedroom with this elegant two short mirror and two bottom drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/sets/set1.webp": "Enhance your bedroom with this elegant set1. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "6 door/sets/set2.webp": "Enhance your bedroom with this elegant set2. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/2x bedside drawers.webp": "Enhance your bedroom with this elegant 2x bedside drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/3x2 chest of drawers.webp": "Enhance your bedroom with this elegant 3x2 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/4 chest of drawers.webp": "Enhance your bedroom with this elegant 4 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/4x2 chest of drawers.webp": "Enhance your bedroom with this elegant 4x2 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/5 chest of drawers.webp": "Enhance your bedroom with this elegant 5 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/5x2 chest of drawers.webp": "Enhance your bedroom with this elegant 5x2 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
  "extras/6 chest of drawers.webp": "Enhance your bedroom with this elegant 6 chest of drawers. Constructed with high-quality materials and available in multiple finishes, matching any contemporary decor.",
};

